CREATE TABLE interview_questions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    interview_id  BIGINT                                  NOT NULL,
    question_text TEXT                                    NOT NULL,
    answer_text   TEXT,
    topic         VARCHAR(255),
    evaluation    JSONB,
    order_index   INTEGER,
    CONSTRAINT pk_interview_questions PRIMARY KEY (id)
);

CREATE TABLE interview_templates
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    difficulty       VARCHAR(255),
    technology_stack JSONB,
    CONSTRAINT pk_interview_templates PRIMARY KEY (id)
);

CREATE TABLE interviews
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    template_id   BIGINT                                  NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    start_time    TIMESTAMP WITHOUT TIME ZONE,
    end_time      TIMESTAMP WITHOUT TIME ZONE,
    overall_score DOUBLE PRECISION,
    report_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_interviews PRIMARY KEY (id)
);

ALTER TABLE interviews
    ADD CONSTRAINT uc_interviews_reportid UNIQUE (report_id);

ALTER TABLE interview_questions
    ADD CONSTRAINT FK_INTERVIEW_QUESTIONS_ON_INTERVIEW FOREIGN KEY (interview_id) REFERENCES interviews (id);